---
title: "Ton_FEMglossary"
format: html
editor: visual
---

| Species code | Scientific name | Common name |
|------------------------|------------------------|------------------------|
| `ABBA` | *Abies balsamea* | Balsam fir |
| `ACPE` | *Acer pensylvanicum* | Striped maple |
| `ACRU` | *Acer rubrum* | Red maple |
| `ACSA` | *Acer saccharum* | Sugar maple |
| `BEAL` | *Betula alleghaniensis* | Yellow birch |
| `BEPA` | *Betula papyrifera* | Paper birch |
| `BEPO` | *Betula populifolia* | Gray birch |
| `FAGR` | *Fagus grandifolia* | American beech |
| `FRAM` | *Fraxinus americana* | White ash |
| `OSVI` | *Ostrya virginiana* | American hophornbeam |
| `PIRU` | *Picea rubens* | Red spruce |
| `PIST` | *Pinus strobus* | White pine |
| `POGR` | *Populus grandidentata* | Bigtooth aspen |
| `POTR` | *Populus tremuloides* | Quaking aspen |
| `PRPE` | *Prunus pensylvanica* | Pin cherry |
| `PRSE` | *Prunus serotina* | Black cherry |
| `RUS` | *Rubus spp.* | Brambles genus, including raspberries and blackberries |
| `QURU` | *Quercus rubra* | Northern red oak |
| `TIAM` | *Tilia americana* | American basswood |
| `TSCA` | *Tsuga canadensis* | Eastern hemlock |

: List of four-letter codes for common woody species (and brambles genus) at the study sites.

Bretziella fagacearum

Armillaria mellea

Nitidulidae

Pseudopityophthorus spp.

forest mesophication
